model:
  generator:
    base_channels: 64
    num_residuals: 6
    use_attention: true
    
  discriminator:
    base_channels: 64
    num_layers: 4

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.0002
  betas: [0.5, 0.999]
  save_interval: 10

styles:
  available_styles:
    - ghibli
    - shonen
    - cyberpunk
  default_style: ghibli

augmentation:
  resize: 256
  random_crop: 224
  hflip_prob: 0.5
  color_jitter: [0.2, 0.2, 0.2, 0.1]
